from __future__ import annotations

import os
import tempfile
from dataclasses import dataclass
from pathlib import Path

from .errors import ValidationError
from .models import Bounds, Origin


INFO_KEYS = {
    "lat_north",
    "lat_south",
    "lon_east",
    "lon_west",
    "datum_lat",
    "datum_lon",
}


@dataclass(frozen=True, slots=True)
class InfoData:
    bounds: Bounds
    origin: Origin
    comments: tuple[str, ...]

    def as_dict(self) -> dict[str, object]:
        return {
            "bounds": self.bounds.as_dict(),
            "origin": self.origin.as_dict(),
            "comments": list(self.comments),
        }


def _write_text_atomic(destination: Path, content: str) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary_name = tempfile.mkstemp(
        prefix=f".{destination.name}.", dir=destination.parent, text=True
    )
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(handle, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary_path, destination)
    finally:
        temporary_path.unlink(missing_ok=True)


def write_info_file(
    destination: Path,
    *,
    actual_bounds: Bounds,
    origin: Origin,
    source_id: str,
    source_attribution: str,
    zoom: int,
    requested_bounds: Bounds,
    generator_version: str,
) -> None:
    lines = [
        f"// generated_by = moos-map {generator_version}",
        f"// source = {source_id}",
        f"// attribution = {source_attribution}",
        f"// zoom = {zoom}",
        (
            "// requested_bounds_wsen = "
            f"{requested_bounds.west:.10f},{requested_bounds.south:.10f},"
            f"{requested_bounds.east:.10f},{requested_bounds.north:.10f}"
        ),
        "",
        f"lat_north = {actual_bounds.north:.10f}",
        f"lat_south = {actual_bounds.south:.10f}",
        f"lon_east  = {actual_bounds.east:.10f}",
        f"lon_west  = {actual_bounds.west:.10f}",
        f"datum_lat = {origin.latitude:.10f}",
        f"datum_lon = {origin.longitude:.10f}",
        "",
    ]
    _write_text_atomic(destination, "\n".join(lines))


def parse_info_file(path: Path) -> InfoData:
    if not path.is_file():
        raise ValidationError(f"Missing MOOS info file: {path}")

    values: dict[str, float] = {}
    comments: list[str] = []
    for line_number, original in enumerate(
        path.read_text(encoding="utf-8").splitlines(), 1
    ):
        stripped = original.strip()
        if stripped.startswith("//"):
            comments.append(stripped[2:].strip())
            continue
        content = original.split("//", 1)[0].strip()
        if not content:
            continue
        if content.count("=") != 1:
            raise ValidationError(
                f"Invalid .info syntax at line {line_number}: {original}"
            )
        key, raw_value = (part.strip() for part in content.split("=", 1))
        if key not in INFO_KEYS:
            raise ValidationError(
                f"Unsupported .info key '{key}' at line {line_number}; "
                "pMarineViewer rejects unknown keys"
            )
        if key in values:
            raise ValidationError(f"Duplicate .info key '{key}' at line {line_number}")
        try:
            values[key] = float(raw_value)
        except ValueError as exc:
            raise ValidationError(
                f"Non-numeric .info value for '{key}' at line {line_number}"
            ) from exc

    missing = INFO_KEYS.difference(values)
    if missing:
        raise ValidationError(f"Missing .info keys: {', '.join(sorted(missing))}")

    return InfoData(
        bounds=Bounds(
            west=values["lon_west"],
            south=values["lat_south"],
            east=values["lon_east"],
            north=values["lat_north"],
        ),
        origin=Origin(
            latitude=values["datum_lat"],
            longitude=values["datum_lon"],
        ),
        comments=tuple(comments),
    )


def write_moos_snippet(
    destination: Path,
    *,
    tiff_name: str,
    origin: Origin,
) -> None:
    content = "\n".join(
        [
            "// Generated by moos-map",
            "// Keep the same-basename .tif and .info files together.",
            "// Copy them into the mission directory or add this map folder to",
            "// IVP_IMAGE_DIRS so pMarineViewer can find them.",
            "",
            "// Global mission geodesy:",
            f"LatOrigin  = {origin.latitude:.10f}",
            f"LongOrigin = {origin.longitude:.10f}",
            "",
            "// Add this inside ProcessConfig = pMarineViewer:",
            f"tiff_file = {tiff_name}",
            "",
        ]
    )
    _write_text_atomic(destination, content)
